### ISSUE TITLE
您好，能发我一份吗？谢谢

### ISSUE THREAD

**Issue by hbtom** [xdweixia/AAAI2020_WTNNM#1]
您好，能发我一份吗？谢谢！398208223@qq.com

**Comment by xdweixia** [comment]
Code is available

**Comment by hbtom** [comment]
thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月31日(星期三) 下午5:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xdweixia/AAAI2020_WTNNM] 您好，能发我一份吗？谢谢 (#1)





 
Code is available
